### ISSUE TITLE
How to run this application

### ISSUE THREAD

**Issue by dvmorris** [stormboy/node-raven#2]
This may seem like a dumb question, but how do you actually run this application? I'm trying to run even the test file like this:

    node test\test.js

And I'm getting the following error:

    
    module.js:340
        throw err;
              ^
    Error: Cannot find module './settings'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (C:\Users\david.morris\Downloads\node-raven-master\test\test.js:6:15)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)

**Comment by stormboy** [comment]
Sorry, that test file was never used and should not have been added to the repo.  Please try

    node example/raven.js

**Comment by dvmorris** [comment]
events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Opening \\.\/dev/seria-id/us/dev/seriast_RFA-Z106-RA-PC_RAVEn_v2.3.21-if00-port0: Unknown error code 3

**Comment by stormboy** [comment]
That error is saying it cannot open the device at /dev/seria-id/us/dev/seriast_RFA-Z106-RA-PC_RAVEn_v2.3.21-if00-port0

As I mentioned, you must edit the settings.json file to set the device path to your Raven dongle.  

What platform are you running on?  If on a unix-based system, the device will be addressable somewhere in /dev

By the way, this project is intended as a library more than an application.  The example application publishes output from the raven dongle to a MQTT service.  If you have an MQTT server running, make sure those settings are correct in the settings.json file.

To then use those values, something must subscribe to the topics that this example app publishes to.

**Comment by dvmorris** [comment]
Thanks, this makes more sense now. I am running on Windows, for the record. I will reply once I figure out the other issues I'm having so it will help other Windows users in the future.
